import {drawBossSignature,drawBossHazardOverlay,drawBossImpact,drawFrozenStatus,drawFrostBurst} from './vfx-renderer.mjs';

const names=['裂壳巨兽 · 活石根脉','深渊骑士 · 熔炉烈焰','星骸法王 · 星轨连线','血肉吞噬者 · 血骨肋环','时空猎手 · 钟盘残像','深渊模仿者 · 王冠武器镜像'];
const colors=['#90bd79','#db8d72','#9ea9ef','#e0787f','#74c7df','#ffd66e'];
const overlay=document.createElement('section');overlay.style.cssText='position:fixed;z-index:2000;inset:0;overflow:auto;background:#040605;color:#efe5d0;font-family:Segoe UI,Microsoft YaHei,sans-serif;padding:28px';overlay.innerHTML='<h1 style="margin:0 0 7px;font-size:26px">v7.1 · 六首领特效与冰冻状态验收</h1><p style="margin:0 0 20px;color:#9ea9a2">每位首领使用独立形状语言；下方冰冻状态没有矩形描边。</p><canvas width="1440" height="950" style="display:block;width:min(1440px,100%);margin:auto;background:#070b0c;border:1px solid #35413d;image-rendering:auto"></canvas>';
document.body.append(overlay);document.getElementById('modal')?.close();const canvas=overlay.querySelector('canvas'),ctx=canvas.getContext('2d');

function panel(x,y,w,h){ctx.fillStyle='#0b1213';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#293735';ctx.strokeRect(x+.5,y+.5,w-1,h-1);const glow=ctx.createRadialGradient(x+w/2,y+h*.58,5,x+w/2,y+h*.58,w*.4);glow.addColorStop(0,'rgba(80,100,95,.14)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(x,y,w,h);}
function body(x,y,color,boss=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='#15191a';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.shadowColor=color;ctx.shadowBlur=9;ctx.beginPath();ctx.ellipse(0,boss?-38:-25,boss?31:19,boss?48:31,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#050707';ctx.beginPath();ctx.ellipse(0,3,boss?42:27,boss?10:7,0,0,Math.PI*2);ctx.fill();ctx.restore();}
function frame(now){const t=now/1000;ctx.clearRect(0,0,canvas.width,canvas.height);for(let i=0;i<6;i++){const col=i%3,row=Math.floor(i/3),x=30+col*460,y=35+row*370,w=430,h=335,cx=x+w/2,cy=y+205;panel(x,y,w,h);ctx.fillStyle='#d7c8ad';ctx.font='600 19px Segoe UI, Microsoft YaHei';ctx.textAlign='center';ctx.fillText(names[i],cx,y+34);ctx.fillStyle='#748782';ctx.font='12px Segoe UI, Microsoft YaHei';ctx.fillText(`BOSS ${String(i+1).padStart(2,'0')} · 独立施法轮廓`,cx,y+56);const hazard={kind:i%3===0?'circle':i%3===1?'line':'cone',x:cx,y:cy,r:82,range:126,length:250,width:50,angle:t*.08,arc:1.18,color:colors[i],life:.4,max:1};drawBossHazardOverlay(ctx,hazard,t,i+1);body(cx,cy+7,colors[i],true);drawBossSignature(ctx,{x:cx,y:cy,r:105,color:colors[i],floor:i+1,phase:'cast',seed:i*73},(t*.16+i*.1)%1);}
  const y=805;ctx.fillStyle='#dbcdb5';ctx.font='600 20px Segoe UI, Microsoft YaHei';ctx.textAlign='left';ctx.fillText('冰冻 / 减速状态：冰壳、地面霜裂与寒雾',42,y-22);for(let i=0;i<3;i++){const x=440+i*260;body(x,y+72,'#879994',i===2);drawFrozenStatus(ctx,{x,y:y+72,r:i===2?27:14,boss:i===2,id:i+1},t);drawFrostBurst(ctx,{x,y:y+48,r:i===2?62:38,seed:i*91},(t*.7+i*.19)%1);}requestAnimationFrame(frame);}requestAnimationFrame(frame);
