import {TILE,COLS,ROWS,clamp,distance,center,createMap,walkable,findPath,lineOfSight,moveBody,rarities,weaponInfo,makeItem,makeGoldenItem,makePlayer,playerStats,enemyScale} from './engine.mjs';
const $=id=>document.getElementById(id),canvas=$('arena'),ctx=canvas.getContext('2d'),modal=$('modal');
const floorNames=['苔影遗迹','赤烬矿坑','永夜圣所','血肉深井','逆时回廊','王权终庭'];
const bossProfiles=[
  {name:'裂壳巨兽',color:'#90bd79',lives:2,forms:['玄甲沉眠','裂壳狂暴'],moves:['mark','shards','charge']},
  {name:'深渊骑士',color:'#db8d72',lives:3,forms:['盾墙姿态','双刃姿态','黑雾骑士'],moves:['charge','cross','summon','ring']},
  {name:'星骸法王',color:'#9ea9ef',lives:4,forms:['追星法杖','旋转星环','陨星王冠','虚空核心'],moves:['aimed','ring','meteor','rifts','teleport']},
  {name:'血肉吞噬者',color:'#e0787f',lives:8,forms:['饥渴之躯','骨甲增生','寄生母巢','腐血喷涌','百足狂奔','吞噬盛宴','万骨王座','赤月暴君'],moves:['devour','toxic','boneRing','summon','charge','rifts','cross','storm']},
  {name:'时空猎手',color:'#74c7df',lives:8,forms:['初刻猎弓','残像步法','双生时线','停滞领域','逆流之身','断秒箭阵','轮回猎场','永恒狩猎'],moves:['rewind','clone','stasis','aimed','teleport','cross','ring','storm']},
  {name:'深渊模仿者',color:'#ffd66e',lives:8,forms:['铁壁之影','猎影之弦','奥术之瞳','三相复制','黄金裁决','逐日箭雨','星铸天灾','终焉化身'],moves:['sword','bow','staff','summon','teleport','cross','ring','storm']}
];
const bossNames=bossProfiles.map(b=>b.name);
const rooms={ruins:{name:'断碑回廊',accent:'#89b099',desc:'破碎石碑与潮湿苔痕'},garden:{name:'荧苔花园',accent:'#76c19f',desc:'发光菌毯蔓过石缝'},forge:{name:'赤烬熔炉',accent:'#dd9169',desc:'冷却的熔岩沟壑'},library:{name:'禁书藏库',accent:'#9a9de1',desc:'倒塌书架围成迷阵'},sanctum:{name:'月蚀圣所',accent:'#d4b27b',desc:'古老祭坛守望深渊'},observatory:{name:'星穹观测台',accent:'#8cb9df',desc:'星图刻在黑色地砖上'}};
const roomPools=[['ruins','garden','library'],['forge','library','observatory'],['sanctum','observatory','forge'],['forge','sanctum','garden'],['library','observatory','sanctum'],['observatory','sanctum','ruins']];
const enemyPools=[
  ['crawler','crawler','brute','archer'],
  ['crawler','brute','archer','wraith','splitter'],
  ['brute','archer','wraith','splitter','shaman','assassin','summoner'],
  ['brute','wraith','splitter','shaman','assassin','summoner'],
  ['wraith','splitter','shaman','assassin','assassin','summoner','brute'],
  ['brute','wraith','splitter','shaman','assassin','summoner','summoner']
];
const skillInfo={dash:{name:'暗影闪避',cost:18},spin:{name:'旋风斩',cost:32},frost:{name:'冰霜冲击',cost:45}};
const classSkills={sword:{dash:{name:'铁壁突进',cost:18},spin:{name:'裂地横扫',cost:32},frost:{name:'剑气震荡',cost:45}},bow:{dash:{name:'猎影翻滚',cost:18},spin:{name:'多重箭雨',cost:32},frost:{name:'穿心标记',cost:45}},staff:{dash:{name:'相位闪现',cost:18},spin:{name:'奥术漩涡',cost:32},frost:{name:'霜火风暴',cost:45}}};
const rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)];
let p=makePlayer(),map=createMap(),floor=1,wave=0,enemies=[],shots=[],effects=[],drops=[],hazards=[],path=[],target=null,roomKind='ruins';
let running=false,paused=true,cleared=false,finished=false,elapsed=0,last=0,uiClock=0,chosen='sword',repath=0,aim={x:520,y:240},held=false;
let toastTime=0,bannerTime=0,screenShake=0,screenFlash=0,screenFlashColor='#f7e4b1',logs=[],stock=[],refreshCount=0,shopTab='buy',pendingTalents=0,currentModal='start';
let soundEnabled=false,audio=null,enemyId=0,lootId=0,shopVisits=0,eliteNext=false,eliteRound=false;
const keys=new Set();
let best=null;try{best=JSON.parse(localStorage.getItem('abyss-best-v1'));}catch{}
if(best&&Number.isFinite(best.kills))$('best').textContent=`本机纪录：${best.won?'已通关':`第 ${best.floor} 层`} · ${best.kills} 击杀`;
function tone(freq=220,duration=.07,type='triangle',volume=.03){if(!soundEnabled)return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function log(text){logs.unshift(text);logs=logs.slice(0,5);$('log').replaceChildren(...logs.map(t=>{const el=document.createElement('p');el.textContent=t;return el;}));}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastTime=2.5;}
function banner(text){$('wave-banner').textContent=text;$('wave-banner').classList.add('show');bannerTime=2.7;}
function textEffect(x,y,text,color='#efce91'){effects.push({type:'text',x,y,text,color,life:.9,max:.9});}
function burst(x,y,color,n=10){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),speed=rand(45,185),life=rand(.28,.75);effects.push({type:'particle',x,y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed-25,size:rand(2,5),glow:i%3===0,color,life,max:life});}}
function ring(x,y,r,color,width=3){effects.push({type:'ring',x,y,r,color,width,life:.55,max:.55});}
function rune(x,y,r,color){effects.push({type:'rune',x,y,r,color,angle:rand(0,Math.PI*2),life:.75,max:.75});}
function flash(color='#f7e4b1',strength=.16){screenFlash=Math.max(screenFlash,strength);screenFlashColor=color;}
function openModal(type,html){if(currentModal==='talent'&&modal.open&&type!=='talent'&&type!=='result')return;if(type==='start')running=false;currentModal=type;paused=true;held=false;keys.clear();$('modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function closeModal(){modal.close();currentModal='';if(running&&!finished)paused=false;canvas.focus();}
function canAct(){return running&&!paused&&!finished;}
function itemIcon(item){return item.slot==='weapon'?weaponInfo[item.kind].symbol:item.slot==='armor'?'⛨':'◈';}
function skillInfoFor(name){return classSkills[p.equipment.weapon.kind]?.[name]||skillInfo[name];}
function weaponColor(item=p.equipment.weapon){return rarities[item?.rarity||0]?.color||'#b8c8bb';}
function weaponImpact(x,y,item=p.equipment.weapon){const rarity=item?.rarity||0,color=weaponColor(item);burst(x,y,color,[3,7,12,18,28][rarity]);if(rarity>=1)ring(x,y,18+rarity*7,color,1+rarity);if(rarity>=2)ring(x,y,12+rarity*5,'#ffffff',1);if(rarity>=3)rune(x,y,24+rarity*7,color);if(rarity>=4){ring(x,y,58,'#fff2ad',4);flash(color,.07);screenShake=Math.max(screenShake,3);}}
function weaponAttackEffect(item=p.equipment.weapon){const rarity=item?.rarity||0,color=weaponColor(item),kind=item?.kind||'sword';if(rarity>=1)burst(p.x+Math.cos(p.facing)*20,p.y+Math.sin(p.facing)*20,color,4+rarity*3);if(rarity>=2)ring(p.x,p.y,22+rarity*7,color,rarity);if(rarity>=3)rune(p.x,p.y,30+rarity*5,color);if(rarity>=4){ring(p.x,p.y,62,'#fff0a6',4);ring(p.x,p.y,86,color,2);flash('#ffd66e',.055);}if(kind==='staff'&&rarity>=2)ring(p.x+Math.cos(p.facing)*25,p.y+Math.sin(p.facing)*25,18+rarity*3,color,2);}
function firePlayerShot(angle,damage,weapon=p.equipment.weapon,magic=weapon.kind==='staff'){const color=weaponColor(weapon),rarity=weapon?.rarity||0;shots.push({x:p.x,y:p.y,vx:Math.cos(angle)*(460+rarity*18),vy:Math.sin(angle)*(460+rarity*18),r:(magic?7:5)+Math.floor(rarity/2),life:1.05,damage,crit:false,friendly:true,magic,weapon,color,rarity});}
function itemStats(item){return [item.attack?`攻击 +${item.attack}`:'',item.armor?`护甲 +${item.armor}`:'',item.crit?`暴击 +${item.crit}%`:'',item.leech?`命中吸血 ${item.leech}%`:'',item.enhance?`强化 +${item.enhance}`:''].filter(Boolean).join(' · ');}
function compare(item){const old=p.equipment[item.slot];return ['attack','armor','crit','leech'].map((key,i)=>{const delta=item[key]-(old?.[key]||0);return delta?`${['攻击','护甲','暴击','吸血'][i]} ${delta>0?'+':''}${delta}${i>1?'%':''}`:'';}).filter(Boolean).join(' / ')||'属性相同';}
function itemCard(item,index,context){const sell=price(item,true);return `<div class="item-card ${item.golden?'golden-item':''}" style="--item:${rarities[item.rarity].color}"><strong>${itemIcon(item)} ${item.name}${item.enhance?` +${item.enhance}`:''}</strong><p>${rarities[item.rarity].name}${item.shopOnly?' · 商店独占，怪物不会掉落':''} · ${itemStats(item)}<br>相比已装备：${compare(item)}</p>${context==='buy'?`<button data-buy="${index}" ${p.gold<price(item)?'disabled':''}>购买 · ${price(item)} 金</button>`:`<button data-equip="${index}">装备</button>${context==='sell'?`<button data-sell="${index}">出售 · ${sell} 金</button>`:''}`}</div>`;}
function price(item,sell=false){const value=item.shopPrice||22+item.rarity*22+(item.enhance||0)*20;return Math.round(value*(sell?.42:1));}
function startScreen(){openModal('start',`<div class="modal-eyebrow">A DESCENT INTO THE UNKNOWN</div><h2 class="modal-title">深渊拾荒者</h2><p class="modal-subtitle">六层遗迹，十八场战斗，六位会变形的首领。<br>越深入，怪物成长越快；锻造武器并准备迎接八命首领。</p><div class="weapon-grid">${Object.entries(weaponInfo).map(([key,w])=>`<button class="weapon-choice ${key===chosen?'selected':''}" data-weapon="${key}"><span class="weapon-symbol">${w.symbol}</span><strong>${w.name}</strong><small>${key==='sword'?'近战横扫 · 攻速快<br>贴身战斗，打击多个目标':key==='bow'?'远程射击 · 灵活<br>保持距离，逐个击破':'奥术弹 · 范围爆炸<br>火力更强，攻击较慢'}</small></button>`).join('')}</div><button class="primary wide" data-action="start">踏入深渊 →</button><p class="modal-note">WASD / 鼠标点击移动 · 点击敌人 / 空格攻击<br>Shift 闪避 · 1 / 2 技能 · Q 药水 · I 背包 · B 商店（战后）<br>完整远征约 25–40 分钟。刷新页面将开始新一局。</p>`);}
function start(){p=makePlayer(chosen);floor=1;wave=0;roomKind='ruins';map=createMap(1,roomKind);enemies=[];shots=[];effects=[];drops=[];hazards=[];path=[];target=null;elapsed=0;logs=[];pendingTalents=0;shopVisits=0;eliteNext=false;finished=false;running=true;closeModal();log('踏入苔影遗迹。愿火光照见归途。');nextWave();updateUI();}
function safeEnemyPoint(origin,r=12){const choices=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++){const pos=center(x,y);if(walkable(map,pos.x,pos.y,r)&&distance(p,pos)>70&&enemies.every(e=>e.hp<=0||distance(e,pos)>e.r+r+8))choices.push({pos,d:distance(origin,pos)});}choices.sort((a,b)=>a.d-b.d);return choices[0]?.pos||center(12,2);}
function spawnEnemy(type,pos,elite=false){const boss=type==='boss',profile=bossProfiles[floor-1]||bossProfiles.at(-1),scale=enemyScale(floor);const config={crawler:{hp:28,r:12,speed:72,attack:9},brute:{hp:68,r:16,speed:43,attack:17},archer:{hp:35,r:12,speed:48,attack:11},wraith:{hp:42,r:12,speed:98,attack:10},splitter:{hp:57,r:14,speed:62,attack:13},shaman:{hp:49,r:14,speed:42,attack:10},assassin:{hp:39,r:11,speed:116,attack:16},summoner:{hp:64,r:15,speed:38,attack:8},boss:{hp:520,r:27,speed:36,attack:32}}[type]||{hp:28,r:12,speed:72,attack:9};if(!walkable(map,pos.x,pos.y,config.r))pos=safeEnemyPoint(pos,config.r);const health=Math.round(config.hp*scale.health*(elite?1.65:1)),lives=boss?profile.lives:1;enemies.push({id:++enemyId,...pos,type,r:config.r,hp:health,maxHp:health,lifeHp:health,lives,totalLives:lives,phase:1,form:boss?profile.forms[0]:'',speed:config.speed+floor*3,attack:Math.round(config.attack*scale.attack+floor*2),cd:rand(.65,1.5),skill:boss?2.2:2.5,slow:0,hit:0,boss,elite,path:[],pathTimer:0,split:false});}
function spawnPoint(){const choices=[];for(let y=2;y<ROWS-2;y++)for(let x=2;x<COLS-2;x++){const pos=center(x,y);if(walkable(map,pos.x,pos.y,24)&&distance(p,pos)>260&&enemies.every(e=>distance(e,pos)>50))choices.push(pos);}return pick(choices)||center(12,2);}
function nextWave(){cleared=false;wave++;roomKind=pick(roomPools[floor-1]||roomPools.at(-1));map=createMap(floor,roomKind);Object.assign(p,center(12,14));p.secondWindUsed=false;path=[];target=null;shots=[];hazards=[];eliteRound=eliteNext;eliteNext=false;if(wave===3){spawnEnemy('boss',center(12,3));for(let i=0;i<Math.min(7,floor+1);i++)spawnEnemy(i%3===0?'brute':i%2?'archer':'crawler',spawnPoint(),floor>=5&&i===0);banner(`${rooms[roomKind].name} · ${bossNames[floor-1]}`);}else{const pools=enemyPools[floor-1]||enemyPools.at(-1),count=6+floor*2+wave;for(let i=0;i<count;i++){let type=pick(pools);if(floor>=2&&wave>=2&&i===0)type='splitter';if(floor>=3&&i===1)type='shaman';if(floor>=3&&wave===2&&i===2)type='assassin';if(floor>=3&&wave===1&&i===0)type='summoner';const depthElite=floor>=4&&i<floor-3;spawnEnemy(type,spawnPoint(),eliteRound&&i<2||depthElite);}banner(`第 ${floor} 层 · ${rooms[roomKind].name} · ${eliteRound?'精英试炼':`战斗 ${wave} / 3`}`);}log(wave===3?`${bossNames[floor-1]}苏醒了，房间：${rooms[roomKind].name}。`:`${rooms[roomKind].name}：第 ${wave} 场战斗开始。敌人强度已提升至第 ${floor} 层。`);}
function finishWave(){cleared=true;shots=[];hazards=[];target=null;path=[];p.gold+=20+floor*10;shopVisits++;refreshCount=0;generateStock();banner(wave===3?'首领已倒下 · 传送门开启':'战场肃清 · 商人抵达');log(`战斗奖励 +${20+floor*10} 金币。按 B 访问商店。`);if(wave===3){p.potions++;drops.push({id:++lootId,...center(12,5),item:makeItem(floor,Math.random()<.4?3:2)});if(floor===6){for(const d of [...drops])collect(d);endRun(true);}}}
function proceed(){if(!cleared||!canAct())return;for(const d of [...drops])collect(d);if(wave===3){floor++;wave=0;map=createMap(floor);Object.assign(p,center(12,14));p.hp=Math.min(p.maxHp,p.hp+35);log('进入下一层，恢复 35 生命。');}nextWave();updateUI();}
function generateStock(){const owned=new Set([...Object.values(p.equipment),...(p.weapons||[]),...p.inventory].filter(Boolean).map(item=>item.name)),used=new Set(owned);stock=[];for(let i=0;i<4;i++){let item=null;for(let tries=0;tries<80;tries++){const roll=Math.random(),candidate=makeItem(floor,roll<.18?3:roll<.72?2:1);if(!used.has(candidate.name)){item=candidate;break;}}item??=makeItem(floor,i%3+1);if(used.has(item.name))item.name+=`·${['猎手','守望','余烬','秘仪'][i]}`;used.add(item.name);stock.push(item);}let golden=null;for(let tries=0;tries<30;tries++){const candidate=makeGoldenItem(floor);if(!used.has(candidate.name)){golden=candidate;break;}}golden??=makeGoldenItem(floor);if(used.has(golden.name))golden.name+=`·第${shopVisits}号`;stock.splice(Math.floor(Math.random()*5),0,golden);}
function showShop(tab='buy'){if(!cleared){toast('清理本场所有敌人后，商人才会出现。');return;}shopTab=tab;const weapon=p.equipment.weapon,enhance=weapon.enhance||0,cost=45+enhance*35;openModal('shop',`<div class="modal-eyebrow">THE WANDERING MERCHANT · 第 ${shopVisits} 次相逢</div><h2 class="modal-title">烛火商会 <span class="gold" style="font-size:21px;letter-spacing:0">${p.gold} 金</span></h2><p class="modal-subtitle">货架每场战斗更新。购买后进入背包，装备需手动更换。<br>离开时未拾取的战利品会自动收入背包。</p><div class="modal-actions" style="justify-content:flex-start;margin:0 0 18px"><button data-shop="buy" ${tab==='buy'?'class="primary"':''}>购买装备</button><button data-shop="sell" ${tab==='sell'?'class="primary"':''}>背包 / 出售</button><button data-shop="forge" ${tab==='forge'?'class="primary"':''}>锻造 / 补给</button></div>${tab==='buy'?`<div class="inventory-grid">${stock.map((item,i)=>item?itemCard(item,i,'buy'):'<div class="item-card empty">已售出</div>').join('')}</div><div class="modal-actions"><button data-action="refresh" ${p.gold<15+refreshCount*10?'disabled':''}>刷新货架 · ${15+refreshCount*10} 金</button></div>`:tab==='sell'?`<div class="inventory-grid">${p.inventory.length?p.inventory.map((item,i)=>itemCard(item,i,'sell')).join(''):'<p class="empty">背包空空如也。已装备的物品不会被出售。</p>'}</div>`:`<div class="shop-grid"><button data-action="forge" ${p.gold<cost||enhance>=5?'disabled':''}>强化当前武器 +${enhance} → +${Math.min(enhance+1,5)}<span>${enhance>=5?'已满级':`${cost} 金 · 攻击 +5`}</span></button><button data-action="buy-potion" ${p.gold<22||p.potions>=9?'disabled':''}>生命药水（恢复 50% 最大生命）<span>22 金 · 持有 ${p.potions}/9</span></button><button data-action="heal" ${p.gold<18||p.hp>=p.maxHp?'disabled':''}>营火治疗 · 恢复全部生命<span>18 金</span></button><button data-action="vitality" ${p.gold<65?'disabled':''}>坚韧祝福 · 本局最大生命 +20<span>65 金 · 同时恢复 20</span></button></div><p class="modal-note">强化绑定当前武器，最高 +5；换装后旧武器仍保留强化。出售仅返还部分价值。</p>`}<div class="modal-actions"><button data-action="close">返回战场</button><button class="primary" data-action="leave-shop">${wave===3?'进入下一层':'继续战斗'} →</button></div>${wave<2?`<p class="modal-note"><label><input id="elite-choice" type="checkbox" ${eliteNext?'checked':''}> 下一场挑战精英：前两只怪物生命 +50%，击杀赏金 +50%，精英必掉稀有装备</label></p>`:''}`);}
function showInventory(){openModal('inventory',`<div class="modal-eyebrow">YOUR COLLECTION · ${p.inventory.length} / 40</div><h2 class="modal-title">拾荒者行囊</h2><p class="modal-subtitle">更换装备会把旧装备放回背包。战斗已暂停。<br>剩余物品可以在战后商店出售；背包满时战利品留在地上。</p><div class="inventory-grid">${p.inventory.length?p.inventory.map((item,i)=>itemCard(item,i,'inventory')).join(''):'<p class="empty">暂无装备。击败敌人或打开宝箱寻找战利品。</p>'}</div><div class="modal-actions">${cleared?'<button data-shop="sell">前往商店</button>':''}<button class="primary" data-action="close">返回战场</button></div>`);}
function equip(index){const item=p.inventory[index];if(!item)return;if(item.slot==='weapon'){const active=p.equipment.weapon;if(!p.weapons[1]){p.weapons[1]=item;p.inventory.splice(index,1);log(`${item.name}已放入副武器栏，按 3 切换。`);}else{p.inventory.splice(index,1);p.weapons[p.weaponIndex]=item;p.equipment.weapon=item;p.inventory.push(active);log(`切换装备：${item.name}成为当前武器。`);}tone(540);updateUI();if(currentModal==='shop')showShop(shopTab);else showInventory();return;}const old=p.equipment[item.slot];p.equipment[item.slot]=item;p.inventory.splice(index,1);if(old)p.inventory.push(old);log(`装备了${item.name}。`);tone(540);updateUI();if(currentModal==='shop')showShop(shopTab);else showInventory();}
function switchWeapon(){if(!canAct())return;if(!p.weapons?.[1]){toast('还没有副武器，先从战利品或商店获得一把武器。');return;}p.weaponIndex=p.weaponIndex===0?1:0;p.equipment.weapon=p.weapons[p.weaponIndex];path=[];target=null;$('weapon-label').textContent=`${p.equipment.weapon.name} · ${p.equipment.weapon.kind==='sword'?'近战':'远程'}`;toast(`切换至${p.equipment.weapon.name} · ${p.equipment.weapon.kind==='sword'?'近战':'远程'}`);tone(520,.1);updateUI();}
const talentPool=[{id:'power',name:'锋刃',desc:'永久增加本局 5 点攻击'},{id:'vigor',name:'铁心',desc:'最大生命 +25，并恢复 25 生命'},{id:'crit',name:'鹰眼',desc:'暴击率增加 6%'},{id:'leech',name:'汲魂',desc:'命中吸血增加 4%'},{id:'armor',name:'石肤',desc:'护甲增加 3 点'},{id:'haste',name:'疾行',desc:'移动速度增加 8%'},{id:'arcane',name:'奥术蓄能',desc:'最大法力 +20，法力回复 +0.6 / 秒'},{id:'overflow',name:'溢能核心',desc:'法力全满时，主动技能伤害 +30%'},{id:'bloodlust',name:'血战本能',desc:'生命低于 50% 时，造成伤害 +25%'},{id:'executioner',name:'处决印记',desc:'对生命低于 35% 的敌人伤害 +45%'},{id:'secondwind',name:'绝境回响',desc:'每场战斗首次濒死时，恢复 35% 生命与 25 法力'},{id:'alchemy',name:'炼金血脉',desc:'生命药水治疗 +35%，并额外恢复 18 法力'},{id:'echo',name:'技能回响',desc:'释放技能后，下一次普通攻击伤害 +40%'},{id:'thorns',name:'荆棘外壳',desc:'受到近战伤害时反弹 25% 伤害'},{id:'focus',name:'猎手专注',desc:'连续命中同一目标，伤害最多提高 30%'},{id:'unstable',name:'不稳定核心',desc:'技能消耗 +20%，但技能伤害 +45%'},{id:'manaOnCrit',name:'星火回流',desc:'每次暴击恢复 2 点法力'},{id:'manaOnKill',name:'灵魂收割',desc:'每次击杀恢复 4 点法力'}];
function talentScreen(){const available=talentPool.filter(t=>!p.talents?.includes(t.id));const talents=(available.length>=3?available:talentPool).sort(()=>Math.random()-.5).slice(0,3);openModal('talent',`<div class="modal-eyebrow">LEVEL ${p.level} · CHOOSE YOUR PATH</div><h2 class="modal-title">深渊的馈赠</h2><p class="modal-subtitle">本次升级已获得全属性提升，现在从三种构筑天赋中选择一项。</p><div class="weapon-grid">${talents.map(t=>`<button class="weapon-choice" data-talent="${t.id}"><span class="weapon-symbol">✧</span><strong>${t.name}</strong><small>${t.desc}</small></button>`).join('')}</div>`);}
function applyTalent(id){if(!p.talents.includes(id))p.talents.push(id);if(id==='power')p.bonusAttack+=5;if(id==='vigor'){p.maxHp+=25;p.hp=Math.min(p.maxHp,p.hp+25);}if(id==='crit')p.bonusCrit+=6;if(id==='leech')p.bonusLeech+=4;if(id==='armor')p.bonusArmor+=3;if(id==='haste')p.bonusSpeed+=.08;if(id==='arcane'){p.maxMana+=20;p.mana=Math.min(p.maxMana,p.mana+20);p.manaRegen+=.6;}if(id==='secondwind')p.secondWindUsed=false;}
function addXP(amount){p.xp+=amount;while(p.xp>=p.xpGoal){p.xp-=p.xpGoal;p.level++;p.xpGoal=Math.round(p.xpGoal*1.5+10);p.maxHp+=12;p.hp=Math.min(p.maxHp,p.hp+12);p.bonusAttack+=2;p.bonusArmor+=1;p.bonusCrit+=1;p.bonusLeech+=1;p.bonusSpeed+=.02;p.maxMana+=6;p.mana=Math.min(p.maxMana,p.mana+6);p.manaRegen+=.18;pendingTalents++;log(`升至等级 ${p.level}：全属性提升，等待天赋选择。`);}}
function collect(drop){if(!drops.includes(drop))return;if(p.inventory.length>=40){toast('背包已满，请在商店出售装备。');return;}p.inventory.push(drop.item);drops.splice(drops.indexOf(drop),1);log(`拾取 ${rarities[drop.item.rarity].name} · ${drop.item.name}`);textEffect(drop.x,drop.y-15,drop.item.name,rarities[drop.item.rarity].color);tone(750,.09);}
function bossPhase(e){e.lives--;if(e.lives<=0){e.hp=0;return false;}const profile=bossProfiles[floor-1]||bossProfiles.at(-1);e.phase=(e.phase||1)+1;e.form=profile.forms[(e.phase-1)%profile.forms.length];e.maxHp=Math.round(e.lifeHp*(1+(e.phase-1)*.11));e.hp=e.maxHp;e.attack+=Math.round(4+floor*1.5);e.speed=Math.min(118,e.speed+4+floor*.5);e.skill=floor>=4?.7:1.05;e.cd=.5;shots=[];hazards=[];screenShake=12;burst(e.x,e.y,profile.color,52);ring(e.x,e.y,72,profile.color,6);ring(e.x,e.y,122,'#ffffff',2);rune(e.x,e.y,105,profile.color);flash(profile.color,.2);banner(`${profile.name} · ${e.form} · 第 ${e.phase} 命`);log(`${profile.name}变形为「${e.form}」，第 ${e.phase} 命苏醒！`);return true;}
function harmEnemy(e,amount,critical=false){if(e.hp<=0)return;e.hp-=amount;e.hit=.12;textEffect(e.x+rand(-8,8),e.y-20,`${critical?'暴击 ':''}${Math.round(amount)}`,critical?'#f3d785':'#d4e6d8');burst(e.x,e.y,e.type==='wraith'?'#ae97dc':e.type==='shaman'?'#82d4b0':'#adb789',critical?9:4);if(critical){ring(e.x,e.y,28,'#f6dc8b',2);flash('#f6dc8b',.035);}if(p.talents?.includes('focus')){if(p.comboTarget===e.id&&p.comboTimer>0)p.comboBonus=Math.min(.3,(p.comboBonus||0)+.04);else{p.comboTarget=e.id;p.comboBonus=0;}p.comboTimer=2.5;}const stats=playerStats(p);p.hp=Math.min(p.maxHp,p.hp+amount*stats.leech/100);if(critical&&p.talents?.includes('manaOnCrit'))p.mana=Math.min(p.maxMana,p.mana+2);if(e.hp<=0){if(e.boss&&amount<90000&&e.lives>1){bossPhase(e);return;}e.hp=0;p.kills++;if(p.talents?.includes('manaOnKill'))p.mana=Math.min(p.maxMana,p.mana+4);const coins=Math.round((e.boss?75:rand(5,11))*(1+floor*.18)*(eliteRound?1.5:1));p.gold+=coins;addXP(e.boss?75:10+floor*3);burst(e.x,e.y,e.boss?'#f4c384':'#6d9682',e.boss?54:14);if(e.elite||e.boss)rune(e.x,e.y,e.boss?92:42,e.boss?'#efb27b':'#c9a8e8');if(e.type==='splitter'&&!e.split){for(let i=0;i<2;i++)spawnEnemy('crawler',{x:e.x+rand(-25,25),y:e.y+rand(-25,25)});log('裂壳怪碎裂成两只幼体！');}if(e.elite||Math.random()<.28)drops.push({id:++lootId,x:e.x,y:e.y,item:makeItem(floor,e.elite?2:null)});if(e.boss){screenShake=7;flash('#f2bd7c',.12);log(`${bossNames[floor-1]}被彻底击败！`);}if(target===e)target=null;}}
const bossMoveNames={mark:'覆地重压',shards:'裂壳飞棘',charge:'狂暴冲撞',cross:'十字剑气',summon:'深渊唤从',ring:'死亡轮舞',aimed:'追猎星弹',meteor:'陨星坠落',rifts:'三重裂口',teleport:'虚空换位',devour:'血肉吞噬',toxic:'腐血喷泉',boneRing:'万骨环爆',storm:'终焉风暴',rewind:'逆流回溯',clone:'时光分身',stasis:'停滞领域',sword:'裁决横斩',bow:'逐日箭雨',staff:'星铸爆裂'};
function bossProjectile(e,angle,speed,damage,color,r=7){shots.push({x:e.x,y:e.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r,life:4.5,damage,friendly:false,color});}
function bossVolley(e,count,speed,damage,color,offset=0){for(let i=0;i<count;i++)bossProjectile(e,i*Math.PI*2/count+offset,speed,damage,color);ring(e.x,e.y,64,color,3);}
function bossHazard(x,y,r,damage,color,labelText='闪避！',life=1.15,mana=0){hazards.push({x:clamp(x,65,975),y:clamp(y,65,655),r,life,max:life,damage,color,label:labelText,mana});}
function bossCharge(e,power=1.35){const angle=Math.atan2(p.y-e.y,p.x-e.x);for(let i=0;i<9;i++)moveBody(map,e,Math.cos(angle)*16,Math.sin(angle)*16);bossHazard(e.x,e.y,58,e.attack*power,'#ef9a72','冲击！',.62);ring(e.x,e.y,46,'#f0b078',4);}
function bossTeleport(e,color){const old={x:e.x,y:e.y},dest=spawnPoint();Object.assign(e,dest);ring(old.x,old.y,42,color,3);ring(e.x,e.y,52,color,4);rune(e.x,e.y,38,color);}
function bossSummon(e,count=2){if(enemies.filter(other=>other.hp>0).length>=22)return;const pool=floor>=5?['assassin','summoner','wraith']:floor>=3?['wraith','splitter','shaman']:['crawler','archer'];for(let i=0;i<count;i++)spawnEnemy(pick(pool),{x:e.x+rand(-75,75),y:e.y+rand(-60,60)},floor>=5&&i===0);}
function castBossMove(e,move){const profile=bossProfiles[floor-1]||bossProfiles.at(-1),phase=e.phase||1,color=profile.color,angle=Math.atan2(p.y-e.y,p.x-e.x),damage=e.attack*(1+phase*.045);if(move==='mark')bossHazard(p.x,p.y,88+floor*5,damage*1.35,color,'碎地！');if(move==='shards')bossVolley(e,10+phase*2,165+phase*12,damage*.55,color,elapsed*.15);if(move==='charge')bossCharge(e,1.25+phase*.05);if(move==='cross')bossVolley(e,phase>=5?12:8,190+floor*12,damage*.62,color,phase%2?0:Math.PI/4);if(move==='summon')bossSummon(e,Math.min(4,1+Math.ceil(phase/3)));if(move==='ring')bossVolley(e,12+phase*2,155+phase*13,damage*.58,color,elapsed*.22);if(move==='aimed')for(let i=-3;i<=3;i++)bossProjectile(e,angle+i*.12,245+floor*10,damage*.68,color,6);if(move==='meteor')for(let i=0;i<3+Math.ceil(floor/2);i++)bossHazard(p.x+rand(-165,165),p.y+rand(-135,135),52+phase*2,damage*1.15,color,'陨星！',1.28);if(move==='rifts')for(let i=0;i<3;i++){const a=i*Math.PI*2/3+elapsed*.3;bossHazard(p.x+Math.cos(a)*130,p.y+Math.sin(a)*130,58+phase*3,damage,color,'裂口！',1.35);}if(move==='teleport'){bossTeleport(e,color);bossVolley(e,8,205,damage*.55,color,Math.PI/8);}if(move==='devour'){e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.045);textEffect(e.x,e.y-32,'吞噬恢复','#ff9c9c');burst(e.x,e.y,color,24);bossSummon(e,2);}if(move==='toxic')for(let i=0;i<5;i++)bossHazard(p.x+rand(-180,180),p.y+rand(-145,145),48+phase*2,damage,'#8ed47f','腐血！',1.35);if(move==='boneRing'){bossVolley(e,10+phase,175,damage*.48,'#f0d6b0');bossVolley(e,8+phase,235,damage*.42,color,Math.PI/(8+phase));}if(move==='storm'){bossVolley(e,14+phase,185+phase*8,damage*.46,color,elapsed*.25);for(let i=0;i<4;i++)bossHazard(p.x+rand(-190,190),p.y+rand(-150,150),54,damage*.95,color,'风暴！',1.05);}if(move==='rewind'){e.hp=Math.min(e.maxHp,e.hp+e.maxHp*.05);bossTeleport(e,color);textEffect(e.x,e.y-34,'时间回溯','#9ee9f4');}if(move==='clone'){bossSummon(e,3);bossVolley(e,8,220,damage*.5,color,Math.PI/8);}if(move==='stasis')bossHazard(p.x,p.y,118,damage*.85,color,'法力停滞！',1.45,24);if(move==='sword'){bossCharge(e,1.55);bossHazard(e.x,e.y,92,damage*1.18,'#ffd66e','横斩！',.78);}if(move==='bow')for(let i=-4;i<=4;i++)bossProjectile(e,angle+i*.105,285,damage*.58,'#ffd66e',6);if(move==='staff'){for(let i=0;i<4;i++){const a=i*Math.PI/2+elapsed*.4;bossHazard(p.x+Math.cos(a)*115,p.y+Math.sin(a)*115,62,damage*1.05,'#c6a4ff','奥术！',1.18);}bossVolley(e,8,195,damage*.48,'#ffd66e',Math.PI/8);}ring(e.x,e.y,34,color,3);log(`${profile.name}施展「${bossMoveNames[move]}」！`);}
function bossCast(e){const profile=bossProfiles[floor-1]||bossProfiles.at(-1),phase=e.phase||1,offset=Math.random()<.55?0:Math.floor(Math.random()*profile.moves.length),move=profile.moves[(phase-1+offset)%profile.moves.length];e.skill=Math.max(.9,4.45-floor*.3-phase*.14);castBossMove(e,move);if(floor>=4&&phase>=5&&Math.random()<.4){const second=profile.moves[(phase+2)%profile.moves.length];if(second!==move)castBossMove(e,second);}}
function hitPlayer(amount,source=null){if(p.invuln>0||p.hp<=0)return;const damage=Math.max(2,Math.round(amount*(p.buffs?.ward>0?.5:1)-playerStats(p).armor*.65));p.hp-=damage;p.invuln=.4;screenShake=3;textEffect(p.x,p.y-25,`−${damage}`,'#ff9d88');tone(95,.1,'sawtooth',.025);if(p.talents?.includes('thorns')&&source?.hp>0)harmEnemy(source,Math.max(1,Math.round(damage*.25)));if(p.hp<=0&&p.talents?.includes('secondwind')&&!p.secondWindUsed){p.secondWindUsed=true;p.hp=Math.round(p.maxHp*.35);p.mana=Math.min(p.maxMana,p.mana+25);toast('绝境回响触发！');log('绝境回响救回了你，恢复生命与法力。');return;}if(p.hp<=0){p.hp=0;endRun(false);}}
function damageRoll(mult=1,target=null,normal=false){const stats=playerStats(p),crit=Math.random()*100<stats.crit;let amount=stats.attack*stats.weapon.power*mult*(crit?1.75:1)*(p.buffs?.fury>0?1.5:1);if(p.talents?.includes('overflow')&&p.mana>=p.maxMana-.1)amount*=1.3;if(p.talents?.includes('bloodlust')&&p.hp/p.maxHp<.5)amount*=1.25;if(target&&p.talents?.includes('executioner')&&target.hp/target.maxHp<.35)amount*=1.45;if(target&&p.comboTarget===target.id)amount*=1+(p.comboBonus||0);if(normal&&p.nextAttackBonus>0)amount*=p.nextAttackBonus;return {amount,crit};}
function attack(){if(!canAct()||p.cd.attack>0)return;const stats=playerStats(p),w=stats.weapon;const live=enemies.filter(e=>e.hp>0);const nearest=target?.hp>0?target:live.filter(e=>distance(p,e)<w.range&&lineOfSight(map,p,e)).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(nearest)p.facing=Math.atan2(nearest.y-p.y,nearest.x-p.x);else p.facing=Math.atan2(aim.y-p.y,aim.x-p.x);p.cd.attack=w.delay;tone(p.equipment.weapon.kind==='staff'?320:180,.07,'triangle');weaponAttackEffect(p.equipment.weapon);if(p.equipment.weapon.kind==='sword'){const rarity=p.equipment.weapon.rarity||0;effects.push({type:'slash',x:p.x,y:p.y,angle:p.facing,life:.18,max:.18,r:78+rarity*4,color:weaponColor(p.equipment.weapon),rarity});if(rarity>=2)effects.push({type:'slash',x:p.x,y:p.y,angle:p.facing+.08,life:.23,max:.23,r:60+rarity*5,color:rarity>=4?'#fff4bd':weaponColor(p.equipment.weapon),rarity});for(const e of live){const ang=Math.atan2(e.y-p.y,e.x-p.x)-p.facing;if(distance(p,e)<=w.range+e.r&&Math.cos(ang)>.05&&lineOfSight(map,p,e)){const d=damageRoll(1,e,true);harmEnemy(e,d.amount,d.crit);weaponImpact(e.x,e.y,p.equipment.weapon);}}}else if(nearest){const d=damageRoll(1,nearest,true);firePlayerShot(p.facing,d.amount,p.equipment.weapon,p.equipment.weapon.kind==='staff');shots.at(-1).crit=d.crit;}p.nextAttackBonus=0;}
function skill(name){if(!canAct()||p.cd[name]>0)return;const info=skillInfoFor(name);if(!info)return;const unstable=p.talents?.includes('unstable');const cost=Math.ceil(info.cost*(unstable?1.2:1));if(p.mana<cost){toast(`法力不足，需要 ${cost} 点法力。`);return;}p.mana-=cost;const kind=p.equipment.weapon.kind;if(name==='dash'){if(!walkable(map,p.x,p.y,p.r))Object.assign(p,center(12,14));p.cd.dash=4.2;p.invuln=.45;let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(!dx&&!dy){dx=Math.cos(p.facing);dy=Math.sin(p.facing);}const length=Math.hypot(dx,dy);for(let i=0;i<8;i++){effects.push({type:'ghost',x:p.x,y:p.y,life:.3,max:.3});moveBody(map,p,dx/length*15,dy/length*15);}path=[];if(kind==='sword'){ring(p.x,p.y,42,'#e3b66e',3);for(const e of enemies)if(e.hp>0&&distance(p,e)<55&&lineOfSight(map,p,e)){const d=damageRoll(.65,e);harmEnemy(e,d.amount,d.crit);weaponImpact(e.x,e.y,p.equipment.weapon);}}else if(kind==='bow'){for(const spread of [-.18,0,.18]){const d=damageRoll(.55,null,true);firePlayerShot(p.facing+spread,d.amount,p.equipment.weapon,false);shots.at(-1).crit=d.crit;}}else{ring(p.x,p.y,48,'#a9c8ef',3);rune(p.x,p.y,34,'#9cc9ef');}if(p.talents?.includes('echo'))p.nextAttackBonus=1.4;tone(450,.12);return;}if(kind==='bow'&&name==='spin'){p.cd.spin=9;ring(p.x,p.y,105,'#d3b77a',2);for(let i=0;i<7;i++){const angle=p.facing+(i-3)*.13,d=damageRoll(.5,null,true);firePlayerShot(angle,d.amount,p.equipment.weapon,false);shots.at(-1).crit=d.crit;}burst(p.x,p.y,'#d9b875',18);screenShake=2;tone(260,.2);return;}if(kind==='bow'&&name==='frost'){p.cd.frost=13;const marked=enemies.filter(e=>e.hp>0&&lineOfSight(map,p,e)).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(marked){p.facing=Math.atan2(marked.y-p.y,marked.x-p.x);marked.slow=3;for(const spread of [-.1,0,.1]){const d=damageRoll(.72,marked);firePlayerShot(p.facing+spread,d.amount,p.equipment.weapon,false);shots.at(-1).crit=d.crit;}}ring(p.x,p.y,82,'#9dd9ee',3);rune(p.x,p.y,46,'#9dd9ee');flash('#9dd9ee',.045);tone(700,.2);return;}const frost=name==='frost',radius=kind==='sword'?(frost?115:125):(frost?165:130),power=(kind==='sword'?(frost?1.2:1.75):(frost?1.05:1.65))*(unstable?1.45:1);p.cd[name]=frost?13:9;const color=kind==='staff'?(frost?'#80dfe3':'#b995e8'):(frost?'#9ebed0':'#efcb8b');ring(p.x,p.y,radius,color,5);ring(p.x,p.y,radius*.68,frost?'#c2f5f4':'#fff0ad',2);rune(p.x,p.y,radius*.55,color);burst(p.x,p.y,frost?'#84dce3':'#e4bb78',32);flash(frost?'#83dce3':'#e8bf78',.06);for(const e of enemies)if(e.hp>0&&distance(p,e)<radius&&lineOfSight(map,p,e)){const d=damageRoll(power,e);harmEnemy(e,d.amount,d.crit);if(frost)e.slow=kind==='sword'?1.4:2.5;weaponImpact(e.x,e.y,p.equipment.weapon);}if(p.talents?.includes('echo'))p.nextAttackBonus=1.4;screenShake=3;tone(frost?650:135,.2);}
function potion(){if(!canAct())return;if(p.cd.potion>0){toast('药水冷却中。');return;}if(!p.potions){toast('药水用完了，战后商店可以补充。');return;}if(p.hp>=p.maxHp){toast('生命已满。');return;}p.potions--;p.hp=Math.min(p.maxHp,p.hp+p.maxHp*(p.talents?.includes('alchemy')?.675:.5));if(p.talents?.includes('alchemy'))p.mana=Math.min(p.maxMana,p.mana+18);p.cd.potion=3;ring(p.x,p.y,50,'#8cdfaa');textEffect(p.x,p.y-25,'恢复生命','#94e3ac');tone(720,.2);updateUI();}
function interact(){if(!canAct())return;const near=drops.find(d=>distance(p,d)<90);if(near){collect(near);return;}if(cleared){showShop();return;}toast('靠近战利品可自动拾取。');}
function endRun(won){finished=true;running=false;paused=true;p.hp=Math.max(0,p.hp);const record={won,kills:p.kills,floor,time:Math.round(elapsed)};if(!best||(won&&!best.won)||(won===best.won&&p.kills>best.kills)){best=record;try{localStorage.setItem('abyss-best-v1',JSON.stringify(record));}catch{}}updateUI();openModal('result',`<div class="modal-eyebrow">${won?'THE ABYSS REMEMBERS YOUR NAME':'EVERY DESCENT LEAVES A STORY'}</div><h2 class="modal-title">${won?'带着传说归来':'火光暂时熄灭'}</h2><p class="modal-subtitle">${won?'你击败了终焉化身，穿越六层深渊归来。<br>十八场战斗与六位变形首领，都将记住你的名字。':'深渊收下了这次远征，但没有收走你的勇气。<br>越深入敌人越强，留意首领的变形提示并保留药水。'}</p><div class="result-stats"><div><strong>${p.kills}</strong><span>击败敌人</span></div><div><strong>${p.level}</strong><span>冒险等级</span></div><div><strong>${formatTime(elapsed)}</strong><span>远征用时</span></div></div><button class="primary wide" data-action="restart">开启新的远征 →</button><p class="modal-note">本机最佳纪录已保存。装备、金币和天赋将在新局重置。</p>`);}
function formatTime(t){return `${Math.floor(t/60).toString().padStart(2,'0')}:${Math.floor(t%60).toString().padStart(2,'0')}`;}
function pauseScreen(){if(!running||finished)return;if(modal.open){if(['pause','help','inventory','shop'].includes(currentModal))closeModal();return;}openModal('pause','<div class="modal-eyebrow">TAKE A BREATH</div><h2 class="modal-title">营火仍在燃烧</h2><p class="modal-subtitle">远征已暂停。整理思绪，再次出发。</p><button class="primary wide" data-action="close">继续远征</button><div class="modal-actions"><button data-action="help">操作说明</button><button data-action="confirm-restart">重新开始</button></div>');}
function showHelp(){openModal('help',`<div class="modal-eyebrow">FIELD NOTES</div><h2 class="modal-title">冒险指南</h2><p class="modal-subtitle">清理六层中的两场遭遇战，再击败会变形的首领。第四层起首领拥有八条命。</p><div class="help-grid"><kbd>WASD / 方向键</kbd><span>移动，立即取消鼠标寻路与自动追击。</span><kbd>鼠标左键</kbd><span>点击地面自动绕行；点击敌人持续追击并攻击。</span><kbd>Space / 右键</kbd><span>普通攻击；装备品质越高，攻击光效、弹道和命中特效越华丽。</span><kbd>Shift</kbd><span>当前职业的位移技能，短暂无敌且不能穿墙。</span><kbd>1 / 2</kbd><span>长剑、猎弓与法杖拥有不同的专属技能。</span><kbd>Q</kbd><span>喝药恢复 50% 最大生命，有 3 秒冷却。</span><kbd>I / B</kbd><span>打开背包 / 战后商店，自动暂停。</span><kbd>E</kbd><span>拾取附近装备；战后打开商店。走到传送门进入下一场。</span><kbd>Esc</kbd><span>暂停或关闭菜单。升级天赋必须完成选择。</span></div><p class="modal-note">装备：普通 → 精良 → 稀有 → 史诗 → 黄金限定。<br>深层小兵生命、攻击和精英数量都会加速提高。</p><div class="modal-actions"><button class="primary" data-action="${running?'close':'restart'}">知道了</button></div>`);}
function updateUI(){const stats=playerStats(p);$('chapter').innerHTML=`第${['一','二','三','四','五','六'][floor-1]}层 <span>· ${floorNames[floor-1]}</span>`;$('area-name').textContent=floorNames[floor-1];$('hp-text').textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;$('hp-fill').style.width=`${p.hp/p.maxHp*100}%`;$('mana-text').textContent=`${Math.floor(p.mana)} / ${p.maxMana}`;$('mana-fill').style.width=`${p.mana/p.maxMana*100}%`;$('xp-text').textContent=`${p.xp} / ${p.xpGoal}`;$('xp-fill').style.width=`${p.xp/p.xpGoal*100}%`;$('attack').textContent=stats.attack;$('armor').textContent=stats.armor;$('crit').textContent=`${stats.crit}%`;$('gold').textContent=p.gold;$('level').textContent=`等级 ${p.level}`;$('level-badge').textContent=String(p.level).padStart(2,'0');$('potions').textContent=p.cd.potion>0?`${p.cd.potion.toFixed(1)} 秒 · ${p.potions} 瓶`:`${p.potions} 瓶`;renderPotionTray();$('time').textContent=formatTime(elapsed);$('objective').textContent=!running?(finished?'本次远征已结束':'选择武器，踏入深渊'):cleared?'战场肃清 · B 商店 / 传送门继续':`第 ${wave}/3 场 · 剩余 ${enemies.filter(e=>e.hp>0).length} 个敌人`;for(let i=1;i<=6;i++)$('depth'+i).classList.toggle('active',i===floor);for(const key of ['dash','spin','frost']){$(key+'-cd').textContent=p.cd[key]>0?`${p.cd[key].toFixed(1)} 秒`:'就绪';$(key).classList.toggle('cooling',p.cd[key]>0);}const boss=enemies.find(e=>e.boss&&e.hp>0);$('bossbar').hidden=!boss;if(boss){$('boss-name').textContent=`${bossNames[floor-1]} · ${boss.form||'初始形态'} · ${'◆'.repeat(boss.lives||1)}`;$('boss-health').style.width=`${boss.hp/boss.maxHp*100}%`;}$('equipment').innerHTML=['weapon','armor','ring'].map((slot,i)=>{const item=p.equipment[slot];return `<div class="equip-slot" style="--item:${item?rarities[item.rarity].color:'#728681'}"><span class="equip-icon">${item?itemIcon(item):['†','⛨','◈'][i]}</span><div><strong>${item?item.name+(item.enhance?` +${item.enhance}`:''):['武器','未装备胸甲','未装备指环'][i]}</strong><small>${item?itemStats(item):'探索地牢获取装备'}</small></div></div>`;}).join('');}
function update(dt){
  elapsed+=dt;for(const key in p.cd)p.cd[key]=Math.max(0,p.cd[key]-dt);p.invuln=Math.max(0,p.invuln-dt);p.mana=Math.min(p.maxMana,p.mana+(p.manaRegen||0)*dt);p.comboTimer=Math.max(0,(p.comboTimer||0)-dt);if(p.comboTimer<=0){p.comboTarget=null;p.comboBonus=0;}repath-=dt;
  let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);
  if(dx||dy){path=[];target=null;const len=Math.hypot(dx,dy);dx/=len;dy/=len;p.facing=Math.atan2(dy,dx);$('mode').textContent='键盘移动';}
  else{if(target?.hp>0){const stats=playerStats(p);if(distance(p,target)>stats.weapon.range*.85||!lineOfSight(map,p,target)){if(repath<=0){path=findPath(map,p,target);repath=.3;}}else{path=[];attack();}}if(path.length){let next=path[0],dist=distance(p,next);if(dist<7){path.shift();next=path[0];dist=next?distance(p,next):0;}if(next&&dist>0){dx=(next.x-p.x)/dist;dy=(next.y-p.y)/dist;p.facing=Math.atan2(dy,dx);}}}
  const speed=155*playerStats(p).weapon.speed*(1+(p.bonusSpeed||0));moveBody(map,p,dx*speed*dt,dy*speed*dt);
  if(keys.has(' ')||held)attack();
  for(const e of enemies){if(e.hp<=0)continue;if(!walkable(map,e.x,e.y,e.r)){Object.assign(e,safeEnemyPoint(e,e.r));e.path=[];e.pathTimer=0;textEffect(e.x,e.y-22,'脱困','#9fe3c2');}e.cd-=dt;e.skill-=dt;e.slow=Math.max(0,e.slow-dt);e.hit=Math.max(0,e.hit-dt);e.pathTimer-=dt;const dist=distance(p,e),los=lineOfSight(map,e,p),ranged=['archer','shaman','summoner'].includes(e.type),stop=ranged?235:e.r+p.r+7;
    if(dist>stop||!los){if(e.pathTimer<=0){e.path=findPath(map,e,p);e.pathTimer=.45+Math.random()*.2;}let dest=los?p:e.path[0];if(dest&&distance(e,dest)<8){e.path.shift();dest=e.path[0]||p;}if(dest){const d=Math.max(1,distance(e,dest));moveBody(map,e,(dest.x-e.x)/d*e.speed*(e.slow>0?.38:1)*dt,(dest.y-e.y)/d*e.speed*(e.slow>0?.38:1)*dt);}}
    if(ranged&&dist<330&&los&&e.cd<=0){const a=Math.atan2(p.y-e.y,p.x-e.x),color=e.type==='shaman'?'#7ed5a8':e.type==='summoner'?'#c092e4':'#e6a16d';shots.push({x:e.x,y:e.y,vx:Math.cos(a)*(210+floor*9),vy:Math.sin(a)*(210+floor*9),r:5,life:2.3,damage:e.attack,friendly:false,color});e.cd=Math.max(1.05,1.65-floor*.07);}
    if(!ranged&&dist<e.r+p.r+13&&los&&e.cd<=0){hitPlayer(e.attack,e);e.cd=e.boss?1.2:e.type==='wraith'?.9:1.3;}
    if(e.boss&&e.skill<=0)bossCast(e);
  }
  for(let i=0;i<enemies.length;i++)for(let j=i+1;j<enemies.length;j++){const a=enemies[i],b=enemies[j],d=distance(a,b),min=a.r+b.r;if(a.hp>0&&b.hp>0&&d>0&&d<min){const push=(min-d)*.35;moveBody(map,a,(a.x-b.x)/d*push,(a.y-b.y)/d*push);moveBody(map,b,(b.x-a.x)/d*push,(b.y-a.y)/d*push);}}
  for(const shot of shots){if(shot.life<=0)continue;shot.life-=dt;const steps=Math.ceil(Math.hypot(shot.vx,shot.vy)*dt/6);for(let step=0;step<steps&&shot.life>0;step++){shot.x+=shot.vx*dt/steps;shot.y+=shot.vy*dt/steps;if(!walkable(map,shot.x,shot.y,3)){shot.life=0;burst(shot.x,shot.y,shot.color||(shot.friendly?'#bce0c2':'#e99475'),3);break;}if(shot.friendly){const enemy=enemies.find(e=>e.hp>0&&distance(e,shot)<e.r+shot.r);if(enemy){shot.life=0;harmEnemy(enemy,shot.damage,shot.crit);weaponImpact(shot.x,shot.y,shot.weapon||p.equipment.weapon);if(shot.magic){ring(shot.x,shot.y,58,shot.color||'#92cce6');for(const other of enemies)if(other!==enemy&&other.hp>0&&distance(other,shot)<58&&lineOfSight(map,shot,other))harmEnemy(other,shot.damage*.6);}}}else if(distance(p,shot)<p.r+shot.r){shot.life=0;hitPlayer(shot.damage);}}}
  shots=shots.filter(s=>s.life>0);
  for(const h of hazards){h.life-=dt;if(h.life<=0){const color=h.color||'#ed846b';ring(h.x,h.y,h.r,color);burst(h.x,h.y,color,22);if(distance(p,h)<h.r+p.r){hitPlayer(h.damage);if(h.mana){p.mana=Math.max(0,p.mana-h.mana);textEffect(p.x,p.y-38,`法力 −${h.mana}`,'#9edff2');}}screenShake=5;}}hazards=hazards.filter(h=>h.life>0);
  for(const drop of [...drops])if(distance(p,drop)<25&&p.inventory.length<40)collect(drop);
  enemies=enemies.filter(e=>e.hp>0);
  if(!enemies.length&&!cleared&&running)finishWave();
  if(cleared&&distance(p,center(12,2))<34&&running)proceed();
  if(pendingTalents>0&&running&&!modal.open){pendingTalents--;talentScreen();}
}

// Pixel silhouettes are original, code-native game sprites; no external asset downloads.
const sprites={
  hero:['   hh   ','  hhhh  ','  ffff  ','  feef  ',' ccccc  ','ccccccc ','cctttcc ','  ttt   ','  b b   ',' bb bb  '],
  crawler:['        ',' e    e ',' gggggg ','gggggggg',' gerr eg',' gggggg ','  gggg  ',' g    g '],
  brute:['  hhhh  ',' hhhhhh ',' hhrrhh ','  hhhh  ',' hhhhhhh','hhhhhhhh',' hhhhhh ','  b  b  ',' bb  bb '],
  archer:['  hhhh  ',' hhhhhh ',' hfee h ','  fff   ','  ccc  w',' ccccc w','  ccc ww','  b b  w',' bb bb w'],
  wraith:['   hh   ','  hhhh  ',' hhhhh h',' hhrrhh ',' hhhhhh ','  hhhh  ',' hhhhhh ',' h hh h ','h  h   h'],
  boss:[' h    h ',' hh  hh ',' hhhhhh ',' hhrrhh ','hhhhhhhh','htttttth','hhtttthh',' hhhhhhh',' hh  hh ','hhh  hhh']};
function sprite(type,x,y,scale=3,hit=false,elite=false){const bossColor=bossProfiles[floor-1]?.color||'#9b87b1',palette=type==='hero'?{h:'#e1ccb0',f:'#dbb28b',e:'#273844',c:'#729d9c',t:'#b3c8b3',b:'#394c54'}:type==='crawler'?{g:'#87a779',e:'#627a58',r:'#e9ce8b'}:type==='brute'?{h:'#9c8a75',r:'#ffc192',b:'#4b5152'}:type==='archer'?{h:'#706f5e',f:'#c5c8ac',e:'#d6ac7a',c:'#5c827c',w:'#ba9a68',b:'#43525a'}:type==='wraith'?{h:'#9b92bc',r:'#debcf4'}:type==='boss'?{h:bossColor,r:'#fff0b2',t:'#535f5b'}:{h:floor<=2?'#8caa79':floor<=4?'#ad7661':'#9b87b1',r:'#ffe3a3',t:'#535f5b'};const rows=sprites[type],w=rows[0].length*scale,h=rows.length*scale;ctx.fillStyle='#02090ba0';ctx.beginPath();ctx.ellipse(x,y+11,w*.48,7,0,0,Math.PI*2);ctx.fill();for(let j=0;j<rows.length;j++)for(let i=0;i<rows[j].length;i++){const col=palette[rows[j][i]];if(col){ctx.fillStyle=hit?'#f9f2de':col;ctx.fillRect(Math.round(x-w/2+i*scale),Math.round(y-h/2+j*scale)-5,scale,scale);}}if(elite){ctx.strokeStyle='#e4bb6e';ctx.lineWidth=1;ctx.strokeRect(x-w/2-4,y-h/2-9,w+8,h+8);}}
function drawBossForm(e,t){const profile=bossProfiles[floor-1]||bossProfiles.at(-1),phase=e.phase||1,color=profile.color;ctx.save();ctx.translate(e.x,e.y-5);ctx.strokeStyle=color;ctx.fillStyle=color+'28';ctx.shadowColor=color;ctx.shadowBlur=12+phase*2;ctx.lineWidth=2+Math.min(3,phase*.35);ctx.beginPath();ctx.arc(0,0,e.r+12+Math.sin(t*4)*3,0,Math.PI*2);ctx.fill();ctx.stroke();if(floor===1){for(let i=0;i<Math.min(6,phase+3);i++){const a=i*Math.PI*2/Math.min(6,phase+3);ctx.beginPath();ctx.moveTo(Math.cos(a)*(e.r+4),Math.sin(a)*(e.r+4));ctx.lineTo(Math.cos(a)*(e.r+19),Math.sin(a)*(e.r+19));ctx.stroke();}}if(floor===2){ctx.rotate(e.facing||0);ctx.strokeRect(-e.r-18,-15,11,30);ctx.beginPath();ctx.moveTo(e.r,0);ctx.lineTo(e.r+28,0);ctx.stroke();}if(floor===3){for(let i=0;i<3+Math.min(3,phase);i++){const a=t*(.6+phase*.08)+i*Math.PI*2/(3+Math.min(3,phase));ctx.fillRect(Math.cos(a)*(e.r+22)-3,Math.sin(a)*(e.r+22)-3,6,6);}}if(floor===4){for(let i=0;i<6;i++){const a=i*Math.PI/3+t*.15;ctx.beginPath();ctx.moveTo(Math.cos(a)*e.r,Math.sin(a)*e.r);ctx.quadraticCurveTo(Math.cos(a+.45)*(e.r+20),Math.sin(a+.45)*(e.r+20),Math.cos(a)*(e.r+34),Math.sin(a)*(e.r+34));ctx.stroke();}}if(floor===5){for(let i=0;i<phase;i++){ctx.globalAlpha=.12;ctx.strokeRect(-e.r-i*5,-e.r-i*3,e.r*2+i*10,e.r*2+i*6);}ctx.globalAlpha=1;ctx.beginPath();ctx.arc(0,0,e.r+24,-Math.PI/2,-Math.PI/2+Math.PI*2*(phase/8));ctx.stroke();}if(floor===6){const symbols=['†','⌁','✧'];ctx.font='20px "Segoe UI"';ctx.textAlign='center';for(let i=0;i<3;i++){const a=t*.8+i*Math.PI*2/3;ctx.fillText(symbols[i],Math.cos(a)*(e.r+28),Math.sin(a)*(e.r+28)+6);}}ctx.restore();label(e.form,e.x,e.y-e.r-34,color,11);}
function label(text,x,y,color='#c0d1c5',size=12){ctx.font=`${size}px "Segoe UI","Microsoft YaHei",sans-serif`;ctx.textAlign='center';ctx.fillStyle='#071015';ctx.fillText(text,x+1,y+1);ctx.fillStyle=color;ctx.fillText(text,x,y);}
function drawDropItem(item,x,y){const color=rarities[item.rarity].color,rare=item.rarity>=2;ctx.save();ctx.translate(x,y-10);ctx.fillStyle='#02090baa';ctx.beginPath();ctx.ellipse(0,14,15,5,0,0,Math.PI*2);ctx.fill();ctx.translate(0,-5);ctx.shadowColor=color;ctx.shadowBlur=item.golden?18:rare?10:3;ctx.strokeStyle=color;ctx.fillStyle='#101a1d';ctx.lineWidth=item.golden?3:2;if(item.slot==='weapon'&&item.kind==='sword'){ctx.rotate(-.62);ctx.fillStyle='#d9e0dc';ctx.beginPath();ctx.moveTo(-2,-15);ctx.lineTo(3,-15);ctx.lineTo(4,10);ctx.lineTo(0,15);ctx.lineTo(-3,10);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#c79255';ctx.fillRect(-7,9,14,3);ctx.fillRect(-2,12,4,8);}else if(item.slot==='weapon'&&item.kind==='bow'){ctx.rotate(-.28);ctx.beginPath();ctx.moveTo(-8,-17);ctx.quadraticCurveTo(9,0,-8,17);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#dfd0a1';ctx.beginPath();ctx.moveTo(-8,-17);ctx.lineTo(-8,17);ctx.stroke();ctx.fillStyle=color;ctx.fillRect(-2,-2,13,3);}else if(item.slot==='weapon'&&item.kind==='staff'){ctx.beginPath();ctx.moveTo(0,-19);ctx.lineTo(0,17);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,-21,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#b98955';ctx.fillRect(-3,9,6,9);}else if(item.slot==='armor'){ctx.beginPath();ctx.moveTo(-12,-10);ctx.lineTo(-6,-16);ctx.lineTo(6,-16);ctx.lineTo(12,-10);ctx.lineTo(9,11);ctx.lineTo(0,17);ctx.lineTo(-9,11);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(0,-14);ctx.lineTo(0,13);ctx.stroke();}else{ctx.beginPath();ctx.arc(0,0,11,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#101a1d';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.fillStyle=color;ctx.beginPath();ctx.arc(0,0,3,0,Math.PI*2);ctx.fill();}if(rare){ctx.shadowColor=color;ctx.shadowBlur=item.golden?15:7;ctx.strokeStyle=color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-15,0);ctx.lineTo(-10,0);ctx.moveTo(10,0);ctx.lineTo(15,0);ctx.moveTo(0,-15);ctx.lineTo(0,-10);ctx.stroke();}ctx.restore();}
function draw(t){
  ctx.clearRect(0,0,1040,720);ctx.save();if(screenShake>0){ctx.translate(rand(-screenShake,screenShake),rand(-screenShake,screenShake));screenShake*=.86;}
  const floorPalettes=[['#1a2828','#1b2b2a','#1c2b2b','#192625'],['#292522','#2c2926','#282522','#2a2825'],['#23232d','#252633','#22232e','#242530'],['#2a2024','#2d2227','#261d22','#302328'],['#17262e','#1a2a33','#18242d','#1b2d35'],['#28251c','#2d291e','#242219','#302c20']],floorColors=floorPalettes[floor-1]||floorPalettes.at(-1);
  for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const seed=(x*37+y*61)%17;ctx.fillStyle=floorColors[seed%4];ctx.fillRect(x*TILE,y*TILE,TILE,TILE);ctx.strokeStyle='#0e171a';ctx.lineWidth=1;ctx.strokeRect(x*TILE+.5,y*TILE+.5,TILE-1,TILE-1);if(seed%4===0){ctx.fillStyle='#61706625';ctx.fillRect(x*TILE+7,y*TILE+12,8,2);ctx.fillRect(x*TILE+27,y*TILE+30,4,2);}if(seed%7===0){ctx.strokeStyle='#0c161855';ctx.beginPath();ctx.moveTo(x*TILE+5,y*TILE+3);ctx.lineTo(x*TILE+13,y*TILE+14);ctx.lineTo(x*TILE+11,y*TILE+23);ctx.stroke();}}
  // Inlaid arena rings and broken tiles create a readable battle ground.
  ctx.strokeStyle='#6884751c';ctx.lineWidth=2;ctx.beginPath();ctx.arc(520,350,165,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(520,350,153,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.save();ctx.translate(520+Math.cos(a)*159,350+Math.sin(a)*159);ctx.rotate(a);ctx.fillStyle='#86a38824';ctx.fillRect(-3,-6,6,12);ctx.restore();}
  for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++)if(map[y][x]){const wall=floor===2?'#51483f':floor===4?'#56373d':floor===5?'#344e59':floor===6?'#5d5132':'#3d484b';ctx.fillStyle='#050c1199';ctx.fillRect(x*TILE+6,y*TILE+10,TILE+3,TILE+9);ctx.fillStyle=wall;ctx.fillRect(x*TILE+1,y*TILE-9,TILE-2,TILE+7);ctx.fillStyle=floor===6?'#776841':floor===4?'#70444a':'#526064';ctx.fillRect(x*TILE+2,y*TILE-9,TILE-4,7);ctx.fillStyle='#202d31';ctx.fillRect(x*TILE+1,y*TILE+25,TILE-2,7);ctx.strokeStyle='#172227';ctx.strokeRect(x*TILE+1,y*TILE-9,TILE-2,TILE+8);if((x+y)%3===0){ctx.fillStyle=(bossProfiles[floor-1]?.color||'#7d7660')+'45';ctx.fillRect(x*TILE+4,y*TILE-4,13,4);}}
  for(const [tx,ty] of [[3,3],[22,3],[3,14],[22,14]]){const x=tx*TILE+20,y=ty*TILE+10;const glow=ctx.createRadialGradient(x,y,2,x,y,105);glow.addColorStop(0,'#e6a46128');glow.addColorStop(1,'#d78b4500');ctx.fillStyle=glow;ctx.fillRect(x-105,y-105,210,210);ctx.fillStyle='#493b2c';ctx.fillRect(x-6,y,12,18);ctx.fillStyle='#ba8051';ctx.fillRect(x-7,y-4,14,5);ctx.fillStyle='#dcb16b';ctx.fillRect(x-4,y-11-Math.sin(t*8+tx)*2,8,10);ctx.fillStyle='#f8db94';ctx.fillRect(x-2,y-8,4,6);}
  if(path.length){ctx.strokeStyle='#8fceac4f';ctx.lineWidth=1;ctx.setLineDash([3,6]);ctx.beginPath();ctx.moveTo(p.x,p.y);for(const n of path)ctx.lineTo(n.x,n.y);ctx.stroke();ctx.setLineDash([]);const end=path[path.length-1];ctx.strokeStyle='#9dd3b7';ctx.beginPath();ctx.ellipse(end.x,end.y,10,5,0,0,Math.PI*2);ctx.stroke();}
  if(cleared){const gate=center(12,2);const glow=ctx.createRadialGradient(gate.x,gate.y,1,gate.x,gate.y,80);glow.addColorStop(0,'#66e9d94d');glow.addColorStop(1,'#66e9d900');ctx.fillStyle=glow;ctx.fillRect(gate.x-80,gate.y-80,160,160);ctx.save();ctx.translate(gate.x,gate.y);ctx.scale(1,.65);ctx.strokeStyle='#9febd5';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,26+Math.sin(t*3)*2,0,Math.PI*2);ctx.stroke();ctx.rotate(t);ctx.strokeRect(-19,-19,38,38);ctx.restore();label(wave===3?'进入下一层':'下一场战斗',gate.x,gate.y+45,'#9dddd1');const merchant=center(12,15);sprite('archer',merchant.x,merchant.y,3);label('烛火商会 [B]',merchant.x,merchant.y+28,'#dfbd83');}
  for(const h of hazards){const color=h.color||'#ed856a';ctx.fillStyle=color+'30';ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(h.x,h.y,h.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=color+'42';ctx.beginPath();ctx.arc(h.x,h.y,h.r*(1-h.life/h.max),0,Math.PI*2);ctx.fill();label(h.label||'闪避！',h.x,h.y,color,14);}
  for(const drop of drops){const color=rarities[drop.item.rarity].color;ctx.strokeStyle=color+'50';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(drop.x,drop.y);ctx.lineTo(drop.x,drop.y-35);ctx.stroke();drawDropItem(drop.item,drop.x,drop.y);if(distance(p,drop)<110)label(drop.item.name,drop.x,drop.y-42,color,11);}
  const bodies=[...enemies.filter(e=>e.hp>0),{...p,type:'hero',isPlayer:true}].sort((a,b)=>a.y-b.y);
  for(const e of bodies){if(e===target){ctx.strokeStyle='#ecc79c';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(e.x,e.y+12,e.r+6,9,0,0,Math.PI*2);ctx.stroke();}if(e.isPlayer){ctx.strokeStyle=p.invuln>0?'#d2eee2':'#77b7a37f';ctx.beginPath();ctx.ellipse(e.x,e.y+11,18,9,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=p.invuln>0?.6+Math.sin(t*40)*.25:1;}if(e.boss)drawBossForm(e,t);sprite(e.type,e.x,e.y,e.boss?6:e.type==='brute'?4:3,e.hit>0,e.elite);ctx.globalAlpha=1;if(!e.isPlayer&&!e.boss){ctx.fillStyle='#070f12';ctx.fillRect(e.x-16,e.y-32,32,3);ctx.fillStyle=e.elite?'#dbb878':'#b88476';ctx.fillRect(e.x-16,e.y-32,32*e.hp/e.maxHp,3);if(e.slow>0){ctx.strokeStyle='#97d9e3';ctx.strokeRect(e.x-17,e.y-22,34,36);}}if(e.isPlayer){ctx.save();ctx.translate(p.x+Math.cos(p.facing)*15,p.y+Math.sin(p.facing)*15);ctx.rotate(p.facing);ctx.fillStyle=weaponColor(p.equipment.weapon);ctx.shadowColor=weaponColor(p.equipment.weapon);ctx.shadowBlur=(p.equipment.weapon.rarity||0)*5;ctx.fillRect(0,-2,p.equipment.weapon.kind==='sword'?17:11,4);ctx.fillStyle='#bf9363';ctx.fillRect(-4,-4,5,8);ctx.restore();}}
  for(const s of shots){const color=s.color||(s.friendly?(s.magic?'#9cd9f6':'#d8bd82'):'#e6a16d'),rarity=s.rarity||0;ctx.save();ctx.strokeStyle=color;ctx.lineWidth=(s.magic?4:2)+Math.floor(rarity/2);ctx.shadowColor=color;ctx.shadowBlur=s.friendly?6+rarity*4:3;ctx.beginPath();ctx.moveTo(s.x-s.vx*(.025+rarity*.004),s.y-s.vy*(.025+rarity*.004));ctx.lineTo(s.x,s.y);ctx.stroke();if(s.friendly&&rarity>=2){ctx.strokeStyle=rarity>=4?'#fff4bd':'#ffffff';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(s.x-s.vx*.015+s.vy*.012,s.y-s.vy*.015-s.vx*.012);ctx.lineTo(s.x,s.y);ctx.stroke();}ctx.fillStyle=s.friendly?color:'#ffd3a0';ctx.beginPath();ctx.arc(s.x,s.y,(s.magic?3:2)+rarity*.7,0,Math.PI*2);ctx.fill();if(s.friendly&&rarity>=3){const spark=6+rarity*2;ctx.strokeStyle=rarity>=4?'#fff4bd':color;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(s.x-spark,s.y);ctx.lineTo(s.x+spark,s.y);ctx.moveTo(s.x,s.y-spark);ctx.lineTo(s.x,s.y+spark);ctx.stroke();}ctx.restore();}
  for(const e of effects){ctx.globalAlpha=clamp(e.life/e.max,0,1);if(e.type==='text')label(e.text,e.x,e.y,e.color,14);if(e.type==='particle'){ctx.save();ctx.fillStyle=e.color;if(e.glow){ctx.shadowColor=e.color;ctx.shadowBlur=10;}const s=e.size||3;ctx.fillRect(e.x-s/2,e.y-s/2,s,s);ctx.restore();}if(e.type==='ring'){ctx.save();ctx.strokeStyle=e.color;ctx.lineWidth=e.width||3;ctx.shadowColor=e.color;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(e.x,e.y,e.r*(1-e.life/e.max*.5),0,Math.PI*2);ctx.stroke();ctx.restore();}if(e.type==='rune'){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.angle+(1-e.life/e.max)*1.8);ctx.strokeStyle=e.color;ctx.lineWidth=2;ctx.shadowColor=e.color;ctx.shadowBlur=10;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.moveTo(Math.cos(a)*e.r*.72,Math.sin(a)*e.r*.72);ctx.lineTo(Math.cos(a)*e.r,Math.sin(a)*e.r);}ctx.stroke();ctx.beginPath();ctx.arc(0,0,e.r*(.7+.3*(1-e.life/e.max)),0,Math.PI*2);ctx.stroke();ctx.restore();}if(e.type==='slash'){ctx.save();ctx.strokeStyle=e.color||'#f4e1b1';ctx.lineWidth=e.rarity>=3?7:e.rarity>=1?6:5;ctx.shadowColor=e.color||'#f4e1b1';ctx.shadowBlur=e.rarity>=2?10:3;ctx.beginPath();ctx.arc(e.x,e.y,e.r*(.6+(1-e.life/e.max)*.4),e.angle-1.25,e.angle+1.25);ctx.stroke();ctx.restore();}if(e.type==='ghost'){sprite('hero',e.x,e.y,3);}}ctx.globalAlpha=1;
  const vignette=ctx.createRadialGradient(520,360,170,520,360,620);vignette.addColorStop(0,'#010b1000');vignette.addColorStop(1,'#01090caa');ctx.fillStyle=vignette;ctx.fillRect(0,0,1040,720);
  for(let i=0;i<25;i++){const x=(i*139+Math.sin(t*.3+i)*15)%1000+20,y=(i*83-t*(3+i%3))%680+20;ctx.globalAlpha=.15+Math.sin(t+i)*.12;ctx.fillStyle='#b2c798';ctx.fillRect(x,y,2,2);}ctx.globalAlpha=1;ctx.restore();if(screenFlash>0){ctx.save();ctx.globalAlpha=screenFlash;ctx.fillStyle=screenFlashColor;ctx.fillRect(0,0,1040,720);ctx.restore();}
}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(!paused&&running)update(dt);if(!paused){for(const e of effects){e.life-=dt;if(e.type==='text')e.y-=25*dt;if(e.type==='particle'){e.x+=e.vx*dt;e.y+=e.vy*dt;}}effects=effects.filter(e=>e.life>0);screenFlash=Math.max(0,screenFlash-dt*.8);toastTime-=dt;bannerTime-=dt;if(toastTime<=0)$('toast').classList.remove('show');if(bannerTime<=0)$('wave-banner').classList.remove('show');}draw(now/1000);uiClock+=dt;if(uiClock>.1){updateUI();uiClock=0;}requestAnimationFrame(frame);}
canvas.addEventListener('pointermove',event=>{const rect=canvas.getBoundingClientRect();aim={x:(event.clientX-rect.left)/rect.width*1040,y:(event.clientY-rect.top)/rect.height*720};});
canvas.addEventListener('pointerdown',event=>{if(!canAct())return;canvas.focus();const rect=canvas.getBoundingClientRect();aim={x:(event.clientX-rect.left)/rect.width*1040,y:(event.clientY-rect.top)/rect.height*720};if(event.button===2){held=true;attack();return;}if(event.button!==0)return;const selected=enemies.filter(e=>e.hp>0&&distance(e,aim)<e.r+15).sort((a,b)=>distance(a,aim)-distance(b,aim))[0];if(selected){target=selected;repath=0;$('mode').textContent='自动追击 · WASD 取消';}else if(cleared&&distance(aim,center(12,15))<35){showShop();}else{target=null;path=findPath(map,p,aim);$('mode').textContent='鼠标寻路 · WASD 接管';if(!path.length)toast('无法到达这里，请点击可通行的地面。');}});
canvas.addEventListener('contextmenu',e=>e.preventDefault());window.addEventListener('pointerup',()=>held=false);
window.addEventListener('keydown',event=>{const key=event.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright','tab'].includes(key)&&!modal.open)event.preventDefault();if(event.repeat)return;if(key==='escape'){event.preventDefault();pauseScreen();return;}if(modal.open)return;if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))keys.add(key);if(key==='shift')skill('dash');if(key==='1')skill('spin');if(key==='2')skill('frost');if(key==='q')potion();if(key==='i'&&running)showInventory();if(key==='b'&&running)showShop();if(key==='e')interact();if(key==='?')showHelp();});
window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();held=false;if(running&&!paused)pauseScreen();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pauseScreen();});
modal.addEventListener('cancel',e=>{e.preventDefault();if(['pause','help','inventory','shop','confirm'].includes(currentModal)&&running)closeModal();});
$('modal-content').addEventListener('click',event=>{const button=event.target.closest?.('button');if(button?.dataset.action!=='buy-potion')return;event.preventDefault?.();event.stopImmediatePropagation?.();if(p.gold<59){toast('购买生命药水需要 59 金。');return;}if(p.potions>=9){toast('生命药水已达持有上限。');return;}p.gold-=59;p.potions++;log('购入生命药水。');tone(720,.12);showShop('forge');updateUI();},true);
$('modal-content').addEventListener('click',event=>{const button=event.target.closest?.('button');if(button?.dataset.action!=='heal')return;event.preventDefault?.();event.stopImmediatePropagation?.();const cost=70+floor*25;if(p.gold<cost){toast(`营火治疗需要 ${cost} 金。`);return;}if(p.hp>=p.maxHp){toast('生命已满。');return;}p.gold-=cost;p.hp=p.maxHp;log(`支付 ${cost} 金，营火恢复了全部生命。`);tone(510,.18);showShop('forge');updateUI();},true);
$('modal-content').addEventListener('click',event=>{const button=event.target.closest?.('button');if(!button||button.disabled)return;const capture=event.eventPhase===1;if(capture&&!button.dataset.talent)return;if(button.dataset.talent){applyTalent(button.dataset.talent);log(`获得天赋：${button.querySelector('strong').textContent}`);closeModal();updateUI();event.stopImmediatePropagation?.();return;}if(button.dataset.elixir){buyElixir(button.dataset.elixir);return;}if(capture)event.stopImmediatePropagation?.();if(button.dataset.weapon){chosen=button.dataset.weapon;startScreen();return;}if(button.dataset.shop){showShop(button.dataset.shop);return;}if(button.dataset.equip!==undefined){equip(+button.dataset.equip);return;}if(button.dataset.buy!==undefined){const i=+button.dataset.buy,item=stock[i];if(item&&p.gold>=price(item)&&p.inventory.length<40){p.gold-=price(item);p.inventory.push(item);stock[i]=null;log(`购入${item.name}。`);tone(630);showShop();updateUI();}else if(p.inventory.length>=40)toast('背包已满，请先出售装备。');return;}if(button.dataset.sell!==undefined){const index=+button.dataset.sell,item=p.inventory[index];if(item){p.gold+=price(item,true);p.inventory.splice(index,1);tone(550);showShop('sell');updateUI();}return;}const action=button.dataset.action;if(action==='start')start();if(action==='restart')startScreen();if(action==='close')closeModal();if(action==='help')showHelp();if(action==='confirm-restart')openModal('confirm','<h2 class="modal-title">重新出发？</h2><p class="modal-subtitle">本次远征的装备、金币和天赋会重置。</p><div class="modal-actions"><button data-action="close">继续当前远征</button><button class="primary" data-action="restart">重新选择武器</button></div>');if(action==='leave-shop'){closeModal();proceed();}if(action==='refresh'&&p.gold>=15+refreshCount*10){p.gold-=15+refreshCount*10;refreshCount++;generateStock();showShop();}if(action==='forge'){const w=p.equipment.weapon,cost=45+(w.enhance||0)*35;if(p.gold>=cost&&(w.enhance||0)<5){p.gold-=cost;w.enhance=(w.enhance||0)+1;w.attack+=5;log(`${w.name}强化至 +${w.enhance}。`);tone(280,.2);showShop('forge');}}if(action==='buy-potion'&&p.gold>=22&&p.potions<9){p.gold-=22;p.potions++;showShop('forge');}if(action==='heal'&&p.gold>=18&&p.hp<p.maxHp){p.gold-=18;p.hp=p.maxHp;showShop('forge');}if(action==='vitality'&&p.gold>=65){p.gold-=65;p.maxHp+=20;p.hp+=20;}updateUI();},true);
$('modal-content').addEventListener('change',e=>{if(e.target.id==='elite-choice')eliteNext=e.target.checked;});
$('modal-content').addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.weapon){chosen=button.dataset.weapon;startScreen();return;}if(button.dataset.shop){showShop(button.dataset.shop);return;}if(button.dataset.equip!==undefined){equip(+button.dataset.equip);return;}if(button.dataset.buy!==undefined){const i=+button.dataset.buy,item=stock[i];if(item&&p.gold>=price(item)&&p.inventory.length<40){p.gold-=price(item);p.inventory.push(item);stock[i]=null;log(`购入${item.name}。`);tone(630);showShop();updateUI();}else if(p.inventory.length>=40){toast('背包已满，请先出售装备。');}return;}if(button.dataset.sell!==undefined){const index=+button.dataset.sell,item=p.inventory[index];if(item){p.gold+=price(item,true);p.inventory.splice(index,1);tone(550);showShop('sell');updateUI();}return;}if(button.dataset.talent){const id=button.dataset.talent;if(id==='power')p.bonusAttack+=5;if(id==='vigor'){p.maxHp+=25;p.hp=Math.min(p.maxHp,p.hp+25);}if(id==='crit')p.bonusCrit=(p.bonusCrit||0)+6;if(id==='leech')p.bonusLeech=(p.bonusLeech||0)+4;if(id==='armor')p.bonusArmor=(p.bonusArmor||0)+3;if(id==='haste')p.bonusSpeed=(p.bonusSpeed||0)+.08;log(`获得天赋：${button.querySelector('strong').textContent}`);closeModal();updateUI();return;}const action=button.dataset.action;if(action==='start')start();if(action==='restart')startScreen();if(action==='close')closeModal();if(action==='help')showHelp();if(action==='confirm-restart')openModal('confirm','<h2 class="modal-title">重新出发？</h2><p class="modal-subtitle">本次远征的装备、金币和天赋会重置。</p><div class="modal-actions"><button data-action="close">继续当前远征</button><button class="primary" data-action="restart">重新选择武器</button></div>');if(action==='leave-shop'){closeModal();proceed();}if(action==='refresh'&&p.gold>=15+refreshCount*10){p.gold-=15+refreshCount*10;refreshCount++;generateStock();showShop();}if(action==='forge'){const w=p.equipment.weapon,cost=45+(w.enhance||0)*35;if(p.gold>=cost&&(w.enhance||0)<5){p.gold-=cost;w.enhance=(w.enhance||0)+1;w.attack+=5;log(`${w.name}强化至 +${w.enhance}。`);tone(280,.2);showShop('forge');}}if(action==='buy-potion'&&p.gold>=22&&p.potions<9){p.gold-=22;p.potions++;showShop('forge');}if(action==='heal'&&p.gold>=18&&p.hp<p.maxHp){p.gold-=18;p.hp=p.maxHp;showShop('forge');}if(action==='vitality'&&p.gold>=65){p.gold-=65;p.maxHp+=20;p.hp+=20;showShop('forge');}updateUI();});
$('pause').onclick=pauseScreen;$('help').onclick=showHelp;$('inventory').onclick=()=>running&&showInventory();$('sound').onclick=()=>{soundEnabled=!soundEnabled;$('sound').textContent=`音效：${soundEnabled?'开':'关'}`;$('sound').setAttribute('aria-pressed',String(soundEnabled));tone(500);};$('basic').onclick=attack;$('dash').onclick=()=>skill('dash');$('spin').onclick=()=>skill('spin');$('frost').onclick=()=>skill('frost');$('potion').onclick=potion;$('interact').onclick=interact;
updateUI();startScreen();requestAnimationFrame(frame);

const elixirInfo={haste:{name:'疾行药剂',price:28,desc:'使用后 10 秒内移动速度 +35%',color:'#79d4c5'},fury:{name:'狂怒药剂',price:34,desc:'使用后 10 秒内造成伤害 +50%',color:'#e59a73'},ward:{name:'守护药剂',price:38,desc:'使用后 10 秒内受到伤害 −50%',color:'#9eb9ec'}};
function potionSummary(){const bag=p.elixirs||{haste:0,fury:0,ward:0},active=Object.entries(p.buffs||{}).filter(([,time])=>time>0).map(([kind,time])=>`${elixirInfo[kind].name} ${Math.ceil(time)}秒`);return `生命 ${p.potions} 瓶 · ${Object.values(bag).reduce((a,b)=>a+b,0)} 瓶药剂${active.length?` · ${active.join(' / ')}`:''}`;}
function renderPotionPanel(){if(currentModal!=='shop')return;const content=$('modal-content');if(!content?.querySelector)return;let panel=content.querySelector('#potion-panel');if(!panel){const anchor=content.querySelector('.shop-grid')||content.querySelector('.inventory-grid');if(!anchor)return;panel=document.createElement('div');panel.id='potion-panel';panel.className='potion-shop';anchor.after(panel);}const bag=p.elixirs||{haste:0,fury:0,ward:0};panel.innerHTML=`<div class="potion-shop-title"><span>特殊药剂</span><small>购买后用 Z / X / C 使用</small></div>${Object.entries(elixirInfo).map(([kind,info])=>`<div class="potion-row" style="--item:${info.color}"><div><strong>${info.name}</strong><small>${info.desc} · 持有 ${bag[kind]||0}</small></div><button data-elixir="${kind}" ${p.gold<info.price?'disabled':''}>${info.price} 金</button></div>`).join('')}`;}
function buyElixir(kind){const info=elixirInfo[kind];if(!info)return;if(p.gold<info.price){toast('金币不足。');return;}p.gold-=info.price;p.elixirs??={haste:0,fury:0,ward:0};p.elixirs[kind]++;log(`购入${info.name}。按 ${kind==='haste'?'Z':kind==='fury'?'X':'C'} 使用。`);tone(610,.09);renderPotionPanel();updateUI();}
function useElixir(kind){if(!canAct())return;p.elixirs??={haste:0,fury:0,ward:0};p.buffs??={haste:0,fury:0,ward:0};if(!p.elixirs[kind]){toast(`${elixirInfo[kind].name}用完了，可在战后商店购买。`);return;}if(p.buffs[kind]>0){toast(`${elixirInfo[kind].name}效果还在持续。`);return;}p.elixirs[kind]--;p.buffs[kind]=10;if(kind==='haste')p.bonusSpeed=(p.bonusSpeed||0)+.35;toast(`使用${elixirInfo[kind].name} · ${elixirInfo[kind].desc.split('使用后 ')[1]}`);tone(kind==='fury'?240:kind==='ward'?430:680,.14);setTimeout(()=>{if(p.buffs[kind]>0){p.buffs[kind]=0;if(kind==='haste')p.bonusSpeed=Math.max(0,(p.bonusSpeed||0)-.35);updateUI();}},10000);updateUI();}
if(typeof MutationObserver!=='undefined')new MutationObserver(()=>renderPotionPanel()).observe($('modal-content'),{childList:true});
if(typeof MutationObserver!=='undefined')$('modal-content').addEventListener('click',event=>{const button=event.target.closest?.('button');if(button?.dataset.elixir)buyElixir(button.dataset.elixir);});
window.addEventListener('keydown',event=>{if(modal.open)return;const key=event.key.toLowerCase();if(key==='3')switchWeapon();if(key==='z')useElixir('haste');if(key==='x')useElixir('fury');if(key==='c')useElixir('ward');});
$('switch-weapon').onclick=switchWeapon;
function renderPotionTray(){const tray=$('potion-tray');if(!tray)return;tray.dataset??={};const bag=p.elixirs||{},key=`${p.potions||0}|${bag.haste||0}|${bag.fury||0}|${bag.ward||0}`;if(tray.dataset.state===key)return;tray.dataset.state=key;const life=Array.from({length:Math.min(p.potions||0,9)},()=>'<i class="potion-slot filled" title="生命药水"></i>').join('');const special=[['Z','haste','#79d4c5'],['X','fury','#e59a73'],['C','ward','#9eb9ec']].map(([key,kind,color])=>Array.from({length:bag[kind]||0},()=>`<i class="elixir-slot filled" style="--item:${color}" title="${key} · ${kind}">${key}</i>`).join('')).join('');tray.innerHTML=life+special;tray.title=`生命药水 ${p.potions||0} 瓶 · 特殊药剂 ${Object.values(bag).reduce((a,b)=>a+b,0)} 瓶`;}
function updateSkillLabels(){for(const key of ['dash','spin','frost']){const info=skillInfoFor(key);const state=p.cd[key]>0?`${p.cd[key].toFixed(1)} 秒`:`${info.cost} 法力 · 就绪`;$(`${key}-cd`).textContent=state;const title=$(`${key}-name`);if(title)title.textContent=info.name;}}
const baseUpdateUI=updateUI;updateUI=()=>{baseUpdateUI();$('potions').textContent=potionSummary();renderPotionTray();updateSkillLabels();};
const balancedShowShopBase=showShop;showShop=(tab='buy')=>{balancedShowShopBase(tab);const content=$('modal-content');if(currentModal!=='shop'||!content?.querySelector)return;const subtitle=content.querySelector('.modal-subtitle');if(subtitle)subtitle.innerHTML='货架只出售精良以上且不重复的装备。黄金限定装备属性极强，只能购买，怪物不会掉落。<br>购买后进入背包，装备需手动更换。';const heal=content.querySelector('[data-action="heal"]');if(heal){const cost=70+floor*25;heal.disabled=p.gold<cost||p.hp>=p.maxHp;heal.innerHTML=`营火治疗 · 恢复全部生命<span>${cost} 金</span>`;}const potionButton=content.querySelector('[data-action="buy-potion"]');if(potionButton){potionButton.disabled=p.gold<59||p.potions>=9;potionButton.innerHTML=`生命药水（恢复 50% 最大生命）<span>59 金 · 持有 ${p.potions}/9</span>`;}};
Object.assign(sprites,{shaman:['   hh   ','  hhhh  ',' hhr rh ','  htt   ',' hhhhh  ','  htt   ',' h h h  ',' hh hh  '],assassin:['  h  h  ',' hrrrrh ','  hh h  ',' hhhhh  ','hh tt hh','  ttt   ',' h h h  ','hh   hh '],splitter:['  hhhh  ',' hrrrrh ','hh h h h',' hhhhh  ','  htt   ',' h th   ',' h h h  ','hh   hh '],summoner:['   hh   ','  hhhh  ',' hrrrh  ','  hth   ',' hhhhh  ','hh t th ',' h h h  ','hh   hh ']});
if(typeof setInterval!=='undefined')setInterval(()=>{if(!canAct())return;for(const e of enemies){if(e.hp<=0)continue;e.special=(e.special||0)-.25;if(e.type==='shaman'&&e.special<=0){e.special=4.5;const ally=enemies.filter(other=>other!==e&&other.hp>0&&!other.boss&&other.hp<other.maxHp*.9).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(ally){ally.hp=Math.min(ally.maxHp,ally.hp+ally.maxHp*.14);textEffect(ally.x,ally.y-25,'治疗','#87e2b8');ring(ally.x,ally.y,28,'#78d3a5');}}if(e.type==='summoner'&&e.special<=0&&enemies.filter(other=>other.hp>0).length<15){e.special=5.5;spawnEnemy('crawler',{x:e.x+rand(-30,30),y:e.y+rand(-30,30)});textEffect(e.x,e.y-25,'召唤','#cf9aeb');ring(e.x,e.y,35,'#b78dde');}if(e.type==='assassin'&&e.special<=0){const d=distance(e,p);if(d>80&&d<360&&lineOfSight(map,e,p)){e.special=3.5;const a=Math.atan2(p.y-e.y,p.x-e.x),steps=8;for(let i=0;i<steps;i++)moveBody(map,e,Math.cos(a)*18,Math.sin(a)*18);ring(e.x,e.y,27,'#de8b9b');}}}},250);
